INIT_DST_DICT = {
    "act": 6,
    "request_slots": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "type": 27,
    "price": 57,
    "customerReview": 27,
    "brand": 26,
    "size": 6,
    "pattern": 33,
    "color": 69,
    "sleeveLength": 6,
    "availableSizes": [
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "materials": 6,
    "customerRating": 19
}
DST_DICT = {
    "act": [
        "ASK:GET",
        "REQUEST:COMPARE",
        "REQUEST:GET",
        "INFORM:GET",
        "INFORM:REFINE",
        "REQUEST:ADD_TO_CART",
        "INFORM:DISAMBIGUATE"
    ],
    "request_slots": [
        "materials",
        "color",
        "pattern",
        "price",
        "availableSizes",
        "sleeveLength",
        "size",
        "customerRating",
        "customerReview",
        "brand"
    ],
    "type": [
        "tank top",
        "suit",
        "coat",
        "trousers",
        "vest",
        "CoffeeTable",
        "EndTable",
        "shirt, vest",
        "blouse",
        "Bed",
        "hoodie",
        "Table",
        "CouchChair",
        "tshirt",
        "shirt",
        "shoes",
        "hat",
        "Lamp",
        "joggers",
        "dress",
        "AreaRug",
        "jeans",
        "Sofa",
        "sweater",
        "Shelves",
        "jacket",
        "Chair",
        "None"
    ],
    "price": [
        129.99,
        "$549",
        "$499",
        4.99,
        134.99,
        9.99,
        139.99,
        "$399",
        14.99,
        144.99,
        "affordable",
        "$299",
        19.99,
        149.99,
        24.99,
        154.99,
        "$349",
        29.99,
        34.99,
        164.99,
        39.99,
        169.99,
        "cheap",
        44.99,
        174.99,
        49.99,
        179.99,
        54.99,
        184.99,
        "expensive",
        59.99,
        189.99,
        64.99,
        69.99,
        199.99,
        74.99,
        204.99,
        "$449",
        79.99,
        209.99,
        84.99,
        214.99,
        89.99,
        "$199",
        94.99,
        "$249",
        224.99,
        99.99,
        229.99,
        234.99,
        109.99,
        "$649",
        239.99,
        114.99,
        244.99,
        "$599",
        124.99,
        "None"
    ],
    "customerReview": [
        2.8,
        3.9,
        3.5,
        3.2,
        4.9,
        4.3,
        4.8,
        4.7,
        2.9,
        3.0,
        3.7,
        4.4,
        2.5,
        4.5,
        4.6,
        "good",
        4.0,
        4.1,
        5.0,
        2.6,
        3.6,
        3.1,
        2.7,
        3.8,
        3.3,
        4.2,
        3.4,
        "None"
    ],
    "brand": [
        "Downtown Stylists",
        "Modern Arts",
        "River Chateau",
        "Uptown Studio",
        "North Lodge",
        "Pedals & Gears",
        "212 Local",
        "Nature Photographers",
        "Art Den",
        "Glam Nails",
        "Home Store",
        "Downtown Consignment",
        "Cats Are Great",
        "Brain Puzzles",
        "New Fashion",
        "Yogi Fit",
        "HairDo",
        "Coats & More",
        "Garden Retail",
        "Ocean Wears",
        "Uptown Gallery",
        "Fancy Nails",
        "StyleNow Feed",
        "Global Voyager",
        "Art News Today",
        "The Vegan Baker",
        "None"
    ],
    "size": [
        "XL",
        "M",
        "XXL",
        "S",
        "XS",
        "L",
        "None"
    ],
    "pattern": [
        "holiday",
        "leafy design",
        "vertical design",
        "checkered, plain",
        "plaid",
        "light stripes",
        "dotted",
        "text",
        "plain",
        "checkered",
        "canvas",
        "light spots",
        "multicolored",
        "twin colors",
        "spots",
        "camouflage",
        "leather",
        "heavy vertical stripes",
        "cargo",
        "light vertical stripes",
        "vertical stripes",
        "velvet",
        "horizontal stripes",
        "plain with stripes on side",
        "vertical striples",
        "knit",
        "floral",
        "stripes",
        "denim",
        "radiant",
        "design",
        "heavy stripes",
        "diamonds",
        "None"
    ],
    "color": [
        "white",
        "dark pink, white",
        "wooden",
        "beige",
        "grey, black",
        "dark yellow",
        "olive, black",
        "yellow, brown",
        "red",
        "white, blue",
        "olive",
        "dark red",
        "green",
        "brown",
        "light blue, light green",
        "grey",
        "red, black",
        "white, black, red",
        "blue, green",
        "black, olive",
        "red, white",
        "dark brown",
        "dirty grey",
        "orange",
        "dark pink",
        "light red",
        "blue, white",
        "light grey",
        "dark grey",
        "yellow, white",
        "grey, white",
        "olive, white",
        "orange, purple",
        "light blue",
        "black and white",
        "black",
        "violet",
        "white, red, violet",
        "pink, black",
        "maroon",
        "yellow, black",
        "black, white",
        "black, red",
        "dark green, dark blue",
        "light pink",
        "blue, black",
        "black, grey",
        "brown, white",
        "dark blue",
        "brown, black",
        "purple",
        "white, black",
        "black, orange",
        "dark green",
        "blue",
        "light orange",
        "grey, blue",
        "green, white",
        "dirty green",
        "yellow",
        "green, violet, pink",
        "pink",
        "grey, brown",
        "blue, grey",
        "pink, white",
        "red, white, yellow",
        "white, grey",
        "maroon, white, blue",
        "golden",
        "None"
    ],
    "sleeveLength": [
        "",
        "sleeveless",
        "half",
        "short",
        "full",
        "long",
        "None"
    ],
    "availableSizes": [
        "XL",
        "M",
        "XXL",
        "S",
        "XS",
        "L"
    ],
    "materials": [
        "natural fibers",
        "wood",
        "memory foam",
        "metal",
        "wool",
        "leather",
        "None"
    ],
    "customerRating": [
        2.9,
        3.7,
        3.0,
        4.2,
        3.8,
        3.1,
        4.7,
        3.9,
        3.5,
        4.3,
        3.4,
        4.9,
        5.0,
        4.4,
        "good",
        3.6,
        3.3,
        3.2,
        4.8,
        "None"
    ]
}
